# Generated by Django 4.1.5 on 2023-01-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpCode',
        ),
        migrations.DeleteModel(
            name='VerifyCodeModel',
        ),
    ]
