# Generated by Django 4.1.5 on 2023-02-07 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='در فرمت 09353967479 وارد کنید', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09353967479", regex='/^09(1[0-9]|3[1-9]|2[1-9]|9[0-9])[0-9]{3}[0-9]{4}$/gm')]),
        ),
    ]
