# Generated by Django 4.1.5 on 2023-02-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_alter_income_options_rename_type_income_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='تومان', max_digits=10, verbose_name='مبلغ ریالی'),
        ),
        migrations.AlterField(
            model_name='income',
            name='select',
            field=models.CharField(choices=[('in', 'دخل'), ('out', 'خرج')], max_length=3, verbose_name='نوع هزینه'),
        ),
    ]
