# Generated by Django 4.1.5 on 2023-02-12 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('income', '0004_alter_income_price_alter_income_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(related_name='category', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
