# Generated by Django 4.1.5 on 2023-02-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_alter_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=15, unique=True, verbose_name='آدرس دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=25, verbose_name='عنوان دسته\u200cبندی'),
        ),
    ]
