# Generated by Django 4.1.5 on 2023-02-01 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان اولین بازدید'),
        ),
    ]
